version: '3'
services:
  db:
    image: mongo
    volumes:
      - /var/tmp/scraper_mongo/data/db:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/scraper
    ports:
      - "3000:3000"
    depends_on:
      - db
